import { BP } from '../theme'
import { FileText, FileSpreadsheet, Zap, Download } from '../icons'

function FilePill({ f, onDownload }) {
  const isXls = (f.name || '').toLowerCase().includes('.xls')
  const isFresh = f.tone === 'fresh'
  const ext = (f.name?.split('.').pop() || '').toUpperCase()
  return (
    <div className="rounded-lg p-2.5 flex items-start gap-2.5"
      style={{ background: isFresh ? BP.greenLight : '#F8FAF9', border: `1px solid ${isFresh ? BP.greenLine : BP.border}` }}>
      <div className="flex items-center justify-center shrink-0"
        style={{ width: 32, height: 32, borderRadius: 6, background: 'white', border: `1px solid ${BP.border}`, color: BP.amber }}>
        {isXls ? <FileSpreadsheet size={16} /> : <FileText size={16} />}
      </div>
      <div className="min-w-0 flex-1">
        <div className="t-125 font-semibold truncate" style={{ color: BP.text }}>{f.label || f.name}</div>
        <div className="t-105" style={{ color: BP.textMuted }}>{f.meta || ext}</div>
        {isFresh && (
          <div className="inline-flex items-center gap-1 mt-1 t-10 font-bold px-1.5 py-0.5 rounded-full"
            style={{ background: 'white', color: BP.amber, border: `1px solid ${BP.warnLine}` }}>
            <Zap size={9} fill={BP.amber} /> Just generated
          </div>
        )}
        <button
          onClick={() => onDownload(f.id, f.name)}
          className="flex items-center gap-1 mt-1 t-105 font-semibold"
          style={{ color: BP.greenDark, background: 'none', border: 'none', padding: 0, cursor: 'pointer' }}
        >
          <Download size={10} /> Download
        </button>
      </div>
    </div>
  )
}

// Right-hand "Files & context" panel — ported from the prototype, driven by the
// live generatedFiles list. The most-recently added file is marked "fresh".
export default function FilesPanel({ generatedFiles = [], onDownload, sessionSummary = null }) {
  const files = generatedFiles.map((f, i) => ({ ...f, tone: i === generatedFiles.length - 1 ? 'fresh' : 'stale' }))

  return (
    <div className="flex flex-col shrink-0 border-l" style={{ width: 308, background: BP.panel, borderColor: BP.border }}>
      <div className="flex items-center gap-2 px-4 shrink-0" style={{ height: 56, background: BP.greenDeep, borderBottom: `1px solid ${BP.greenDeeper}` }}>
        <FileText size={16} color="white" />
        <div className="text-white t-135 font-semibold">Files &amp; context</div>
      </div>

      <div className="overflow-y-auto p-4 space-y-4" style={{ flex: 1 }}>
        {sessionSummary && sessionSummary.length > 0 && (
          <div>
            <div className="flex items-center gap-1.5 mb-2 t-11 font-bold tracking-wider" style={{ color: BP.greenDark }}>
              <span style={{ width: 6, height: 6, borderRadius: '50%', background: BP.green }} />
              SESSION SUMMARY
            </div>
            <div className="rounded-lg p-3 t-115 space-y-1" style={{ background: BP.greenLight, border: `1px solid ${BP.greenLine}`, color: BP.text }}>
              {sessionSummary.map((r, i) => (
                <div key={i} className="flex justify-between">
                  <span style={{ color: BP.textMuted }}>{r[0]}</span>
                  <span className="font-semibold">{r[1]}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {files.length > 0 ? (
          <div>
            <div className="flex items-center gap-1.5 mb-2 t-11 font-bold tracking-wider" style={{ color: BP.amber }}>
              <Zap size={12} fill={BP.amber} /> GENERATED BY AGENTS
            </div>
            <div className="space-y-2">
              {files.map((f, i) => <FilePill key={f.id || i} f={f} onDownload={onDownload} />)}
            </div>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center text-center py-12">
            <div className="flex items-center justify-center mb-3"
              style={{ width: 56, height: 56, borderRadius: '50%', border: `2px dashed ${BP.greenLine}`, color: BP.green }}>
              <FileText size={20} />
            </div>
            <div className="t-13 font-semibold" style={{ color: BP.text }}>No files yet</div>
            <div className="t-115 mt-1 px-4" style={{ color: BP.textMuted, lineHeight: 1.4 }}>
              Files you upload and documents the agents generate will appear here during your session.
            </div>
            <div className="mt-4 mx-2 rounded-lg p-3 t-11" style={{ background: BP.greenLight, color: BP.greenDark, lineHeight: 1.45 }}>
              Tip — upload a spreadsheet or report you currently use and the agent will <b>read it directly</b> to understand your metrics.
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
