const FileIcon = ({ size = 14 }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
    <polyline points="14 2 14 8 20 8" />
  </svg>
)

const DownloadIcon = () => (
  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
    <polyline points="7 10 12 15 17 10" />
    <line x1="12" y1="15" x2="12" y2="3" />
  </svg>
)

export default function RightPane({ generatedFiles, onDownload }) {
  return (
    <aside className="right">
      <div className="right-header">
        <FileIcon size={15} />
        Files &amp; context
      </div>
      <div className="right-body">
        {generatedFiles.length === 0 ? (
          <div className="right-empty">
            <div className="right-empty-icon"><FileIcon size={36} /></div>
            <p className="right-empty-title">No files yet</p>
            <p className="right-empty-hint">Files the agents generate will appear here during your session.</p>
            <p className="right-empty-tip">
              <strong>Tip —</strong> upload a spreadsheet and the agent will read it directly to understand your metrics.
            </p>
          </div>
        ) : (
          <div className="right-section">
            <div className="right-section-title generated">
              <span>&#x27F3;</span> GENERATED BY AGENTS
            </div>
            {generatedFiles.map((f) => (
              <div key={f.id} className="file-card">
                <div className="file-card-icon"><FileIcon /></div>
                <div className="file-card-body">
                  <span className="file-card-name">{f.label}</span>
                  <span className="file-card-meta">{f.meta}</span>
                  <span className="file-card-ext">{f.name.split('.').pop()?.toUpperCase()}</span>
                </div>
                <button
                  className="file-download-btn"
                  onClick={() => onDownload(f.id, f.name)}
                  title={`Download ${f.name}`}
                >
                  <DownloadIcon />
                  Download
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </aside>
  )
}
