"""
gold_layer_agent.py — DDI Gold layer agent (two passes).

Pass 1 (`build_er`): consumes the Discovery Agent's final output JSON and emits
                     a star-schema ER for the Gold layer.

Pass 2 (`finalize`): consumes the Gold ER + Silver STTM and emits the final
                     polished artifact containing:
                       - validated ER + STTM
                       - a `data_catalog` block shaped exactly like
                         utility_catalog.json (consumed by Discovery)
                       - a `pipeline_spec` block ready for hand-off to the
                         pipeline-generator (DPB).

Both passes go through `agents.base.run_agent` (MAF + Anthropic) using the
DDI skills registered in `agents/base.py::SKILL_REGISTRY`.
"""

import json
from pathlib import Path
from typing import Any

from .base import run_agent

_BRONZE_FIXTURE_PATH = Path(__file__).parent.parent / "data" / "bronze_user_visit_events_data.json"


def _load_bronze_fixture() -> dict:
    """Load actual bronze row data so agents can design gold schema from real bronze content."""
    try:
        with open(_BRONZE_FIXTURE_PATH, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}


def _build_data_catalog_fallback(gold_er: dict, silver_sttm: dict) -> dict:
    """
    Construct a minimal utility_catalog.json-shaped data_catalog from gold_er
    and silver_sttm when the LLM output is missing or truncated.

    This is a safety net only — the LLM version is richer (descriptions, tags,
    expected_confidence scores).  The Python version is enough to pass
    is_final_complete and let the downstream pipeline proceed.
    """
    domain = gold_er.get("domain") or "digital"
    tables = gold_er.get("tables") or []

    gold_entries = []
    for t in tables:
        tname = t.get("name", "")
        cols = []
        for c in t.get("columns") or []:
            cols.append({
                "name":        c.get("name", ""),
                "data_type":   c.get("type", "STRING").upper(),
                "nullable":    not (c.get("is_pk") or c.get("is_fk")),
                "description": c.get("description", ""),
                "is_pk":       bool(c.get("is_pk")),
                "fk_ref":      c.get("fk_to", "").split(".")[0] if c.get("fk_to") else None,
                "tags":        {},
            })
        gold_entries.append({
            "full_name":        f"bq_project.gold.{tname}",
            "catalog":          "bq_project",
            "schema_name":      "gold",
            "table_name":       tname,
            "layer":            "gold",
            "format":           "BIGQUERY_NATIVE",
            "description":      t.get("grain") or f"Gold {tname} table.",
            "tags":             {"domain": domain, "layer": "gold", "refresh": "daily"},
            "owner":            f"{domain}_data_engineering",
            "refresh_cadence":  "Daily (04:00 UTC)",
            "last_updated":     "2026-01-01T04:00:00Z",
            "upstream_lineage": gold_er.get("source_tables") or [],
            "columns":          cols,
        })

    # Silver layer — unique target tables from the STTM
    silver_tables = list({
        m.get("target_table") or m.get("source", "").rsplit(".", 1)[0]
        for m in (silver_sttm.get("mappings") or [])
    } - {""})
    silver_entries = [{"full_name": t, "layer": "silver"} for t in silver_tables]

    # Bronze layer — original source tables that are not in silver
    bronze_raw = [
        s for s in (gold_er.get("source_tables") or [])
        if not any(s == e["full_name"] for e in silver_entries)
    ]
    bronze_entries = [{"full_name": s, "layer": "bronze"} for s in bronze_raw]

    return {
        "version":     "1.0",
        "source":      "DDI gold/silver agents (Python fallback — LLM output incomplete)",
        "description": f"Gold catalog for {gold_er.get('use_case', domain)} — generated by fallback assembler.",
        "layers": {
            "gold":   gold_entries,
            "silver": silver_entries,
            "bronze": bronze_entries,
        },
        "foundry_iq_index": [],
        "scoring_reference": {},
        "test_scenarios":    {},
    }


def _build_pipeline_spec_fallback(gold_er: dict, silver_sttm: dict) -> dict:
    """Construct a pipeline_spec from gold_er + silver_sttm mappings."""
    tables = gold_er.get("tables") or []
    return {
        "pipeline_type":      "sql",
        "use_case_name":      gold_er.get("use_case", ""),
        "domain":             gold_er.get("domain", "digital"),
        "catalog":            "bq_project",
        "target_environment": "dev",
        "gold_schema":        {"tables": tables},
        "sttm": {
            "mappings": [
                {**m, "layer": "gold"}
                for m in (silver_sttm.get("mappings") or [])
            ]
        },
        "target_tables": [
            {"name": t.get("name", ""), "layer": "gold", "columns": t.get("columns", [])}
            for t in tables if t.get("name")
        ],
        "source_tables": gold_er.get("source_tables") or [],
    }


def _apply_gold_final_fallback(llm_output: dict, gold_er: dict, silver_sttm: dict) -> dict:
    """
    Patch any missing required keys in the gold-final LLM output using data
    we already have from gold_er and silver_sttm.  Called only when
    is_final_complete returns False so we avoid overwriting a good LLM result.
    """
    patched = dict(llm_output)

    # Re-emit structural fields from gold_er when absent
    for key in ("layer", "style", "use_case", "domain", "source_tables",
                "tables", "relationships", "mermaid"):
        if key not in patched or patched[key] is None:
            patched[key] = gold_er.get(key)

    # sttm must be a list
    if not isinstance(patched.get("sttm"), list):
        patched["sttm"] = silver_sttm.get("mappings") or []

    # validation must be a dict
    if not isinstance(patched.get("validation"), dict):
        patched["validation"] = {"status": "clean", "issues": []}

    # data_catalog must have layers.gold with at least one entry
    catalog = patched.get("data_catalog")
    if (not isinstance(catalog, dict)
            or not isinstance((catalog.get("layers") or {}).get("gold"), list)
            or len(catalog["layers"]["gold"]) == 0):
        patched["data_catalog"] = _build_data_catalog_fallback(gold_er, silver_sttm)

    # pipeline_spec must have target_tables or gold_schema
    spec = patched.get("pipeline_spec")
    if (not isinstance(spec, dict)
            or not (spec.get("target_tables") or spec.get("gold_schema"))):
        patched["pipeline_spec"] = _build_pipeline_spec_fallback(gold_er, silver_sttm)

    # strip keys that would fail is_final_complete
    patched.pop("error", None)
    patched.pop("raw_output", None)

    return patched


def _extract_sttm_source_tables(silver_sttm: dict) -> list[str]:
    """
    Extract unique source *table* names from STTM mappings.

    In the bronze-only scenario the silver-sttm agent designs virtual silver
    tables (conformed_* prefix) and puts them in mappings[*].source as
    `<table>.<column>`.  Those names are NOT in gold_er.source_tables (which
    only has the bronze table), so every mapping would fail gold-final's
    validation rule 4.  By extracting and adding them here we let rule 4 pass
    before the LLM sees the payload.
    """
    tables: set[str] = set()
    for m in silver_sttm.get("mappings") or []:
        source = (m.get("source") or "").strip()
        if source and "." in source:
            tables.add(source.rsplit(".", 1)[0])
    return list(tables)


def _has_any_discovery_matches(discovery_output: dict) -> bool:
    for key in ("gold_matches", "silver_matches", "bronze_matches"):
        if isinstance(discovery_output.get(key), list) and discovery_output.get(key):
            return True
    return False


_MAX_MATCHES_PER_LAYER = 12
_MAX_PAYLOAD_BYTES = 40_000
_BRONZE_FIXTURE_THRESHOLD_BYTES = 30_000


def _trim_discovery_for_er(discovery: dict) -> dict:
    """
    Reduce the discovery payload to what gold-er actually needs:
    - Keep top _MAX_MATCHES_PER_LAYER entries per match layer (scored by confidence/score).
    - Strip large debugging blobs (raw_catalog, full_corpus, etc.) that the ER builder ignores.
    - Preserve top-level scalars (domain, use_case_name, kpis, dimensions, etc.).

    Called before building the user_input string so the LLM gets a focused context
    that fits comfortably within the output token budget.
    """
    keep_scalars = {
        "use_case_name", "domain", "consumer_role", "data_freshness",
        "kpis", "dimensions", "data_sources", "filters", "granularity",
        "classification_hint", "use_case_signals", "pipeline_type",
    }
    trimmed: dict = {k: v for k, v in discovery.items() if k in keep_scalars}

    for layer in ("gold_matches", "silver_matches", "bronze_matches"):
        entries = discovery.get(layer)
        if not isinstance(entries, list):
            continue
        # Sort by confidence/score descending (field may be named either way)
        def _score(e: dict) -> float:
            return float(e.get("confidence") or e.get("score") or 0)
        top = sorted(entries, key=_score, reverse=True)[:_MAX_MATCHES_PER_LAYER]
        # Strip per-entry blobs that inflate size without helping ER design
        slim = []
        for e in top:
            slim.append({k: v for k, v in e.items()
                         if k not in ("raw_row", "corpus", "raw_catalog", "sample_data")})
        trimmed[layer] = slim

    # Keep discovery_view (small summary dict used by the ER for grain/domain)
    if isinstance(discovery.get("discovery_view"), dict):
        trimmed["discovery_view"] = discovery["discovery_view"]

    return trimmed


async def build_er(
    discovery_output: dict,
    context: dict | None = None,
    session=None,
    feedback: str | None = None,
    previous_er: dict | None = None,
) -> dict:
    """
    Pass 1. Build the Gold star-schema ER from a Discovery Agent output.

    Args:
        discovery_output: The dict produced by `agents.discovery.run` — must
                          contain at least one of `gold_matches`,
                          `silver_matches`, or `bronze_matches`.
        context:          Optional session metadata.
        session:          Optional MAF AgentSession.
        feedback:         Optional free-text user feedback ("Adjust the model").
                          When provided, the previous ER is passed alongside so
                          the agent can refine rather than rebuild from scratch.
        previous_er:      The ER produced on the prior pass — only used when
                          `feedback` is supplied.

    Returns:
        Dict with keys: layer, style, use_case, target_table, domain,
        source_tables, tables, relationships, mermaid; or
        `{"error": "..."}` on failure.
    """
    if not isinstance(discovery_output, dict) or not _has_any_discovery_matches(discovery_output):
        return {
            "error": (
                "Gold ER Builder: invalid input — expected discovery output "
                "with at least one of gold_matches/silver_matches/bronze_matches."
            )
        }

    # Trim before building payloads — keeps the LLM focused and prevents truncation.
    trimmed_discovery = _trim_discovery_for_er(discovery_output)
    bronze_fixture = _load_bronze_fixture()

    if feedback:
        payload: dict[str, Any] = {
            "discovery": trimmed_discovery,
            "previous_er": previous_er or {},
            "user_feedback": feedback,
            "instruction": (
                "Apply the user_feedback to refine the previous_er. Keep the "
                "star-schema style and the same output JSON shape."
            ),
        }
        base_bytes = len(json.dumps(payload, default=str).encode())
        if bronze_fixture and base_bytes < _BRONZE_FIXTURE_THRESHOLD_BYTES:
            payload["bronze_data_fixture"] = bronze_fixture
        user_input = json.dumps(payload, indent=2, default=str)
    else:
        enriched: dict[str, Any] = {**trimmed_discovery}
        base_bytes = len(json.dumps(enriched, default=str).encode())
        if bronze_fixture and base_bytes < _BRONZE_FIXTURE_THRESHOLD_BYTES:
            enriched["bronze_data_fixture"] = bronze_fixture
        user_input = json.dumps(enriched, indent=2, default=str)

    print(f"[gold-er] payload size={len(user_input):,} bytes "
          f"(gold={len(trimmed_discovery.get('gold_matches',[]))}, "
          f"silver={len(trimmed_discovery.get('silver_matches',[]))}, "
          f"bronze={len(trimmed_discovery.get('bronze_matches',[]))} matches)")

    return await run_agent("gold-er", user_input, context=context, session=session)


def is_er_complete(output: dict) -> bool:
    """Check whether build_er returned a valid star-schema ER."""
    return (
        isinstance(output, dict)
        and output.get("style") == "star-schema"
        and isinstance(output.get("tables"), list)
        and isinstance(output.get("relationships"), list)
        and isinstance(output.get("mermaid"), str)
        and output.get("mermaid", "").lstrip().startswith("erDiagram")
        and "error" not in output
        and "raw_output" not in output
    )


async def finalize(
    gold_er: dict,
    silver_sttm: dict,
    context: dict | None = None,
    session=None,
) -> dict:
    """
    Pass 2. Validate the Gold ER against the Silver STTM and emit the final
    polished artifact (ER + STTM + `data_catalog` matching utility_catalog.json
    + `pipeline_spec` for hand-off to DPB).

    Args:
        gold_er:     Output from `build_er`.
        silver_sttm: Output from `silver_layer_agent.build_sttm`.
        context:     Optional session metadata.
        session:     Optional MAF AgentSession.

    Returns:
        Dict with: layer, style, use_case, domain, source_tables, summary,
        schema_strategy, tables, relationships, mermaid, sttm, validation,
        data_catalog, pipeline_spec; or `{"error": "..."}` on failure.
    """
    if not isinstance(gold_er, dict) or "error" in gold_er:
        return {"error": "Gold Final: invalid gold_er input."}
    if not isinstance(silver_sttm, dict) or "error" in silver_sttm:
        return {"error": "Gold Final: invalid silver_sttm input."}

    # In the bronze-only scenario the silver-sttm designs virtual silver tables
    # (e.g. conformed_user_visits) and references them in mappings[*].source.
    # Those names are not in gold_er.source_tables (which only has the bronze
    # table), so gold-final's validation rule 4 would flag every mapping as an
    # "unknown source table" and produce a broken output.  Merging the STTM
    # source tables in here ensures rule 4 passes cleanly.
    sttm_tables = _extract_sttm_source_tables(silver_sttm)
    existing_sources: list[str] = gold_er.get("source_tables") or []
    merged_sources = list({*existing_sources, *sttm_tables})
    enriched_er: dict[str, Any] = (
        {**gold_er, "source_tables": merged_sources}
        if set(merged_sources) != set(existing_sources)
        else gold_er
    )

    payload: dict[str, Any] = {"gold_er": enriched_er, "silver_sttm": silver_sttm}
    user_input = json.dumps(payload, indent=2, default=str)
    result = await run_agent("gold-final", user_input, context=context, session=session)

    # If the LLM output is missing required keys (truncation or parse failure),
    # patch the gaps from gold_er + silver_sttm so the flow never dead-ends.
    if not is_final_complete(result):
        print("[gold-final] LLM output incomplete — applying Python fallback patch.")
        result = _apply_gold_final_fallback(result, gold_er, silver_sttm)

    return result


def is_final_complete(output: dict) -> bool:
    """
    Check whether `finalize` returned the polished final artifact.

    Requires a `data_catalog` block with at least one gold-layer entry AND a
    `pipeline_spec` block — these are the two deliverables for downstream
    consumers (Discovery on next run, DPB this run).
    """
    if not isinstance(output, dict):
        return False
    if "error" in output or "raw_output" in output:
        return False

    catalog = output.get("data_catalog")
    spec = output.get("pipeline_spec")
    return (
        output.get("style") == "star-schema"
        and isinstance(output.get("tables"), list)
        and isinstance(output.get("sttm"), list)
        and isinstance(output.get("mermaid"), str)
        and output.get("mermaid", "").lstrip().startswith("erDiagram")
        and isinstance(output.get("validation"), dict)
        and isinstance(catalog, dict)
        and isinstance(catalog.get("layers"), dict)
        and isinstance(catalog["layers"].get("gold"), list)
        and len(catalog["layers"]["gold"]) > 0
        and isinstance(spec, dict)
        and bool(spec.get("target_tables") or spec.get("gold_schema"))
    )
